# Generated by Django 4.2.7 on 2026-01-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('failure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='补偿措施名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='补偿措施编码')),
                ('description', models.TextField(blank=True, verbose_name='补偿措施描述')),
                ('measure_type', models.CharField(choices=[('preventive', '预防性'), ('corrective', '纠正性'), ('detection', '检测性'), ('mitigation', '缓解性'), ('redundancy', '冗余性'), ('other', '其他')], default='corrective', max_length=20, verbose_name='措施类型')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本')),
                ('time_required', models.PositiveIntegerField(default=0, verbose_name='所需时间（分钟）')),
                ('effectiveness', models.FloatField(default=0.8, verbose_name='预期效果（0-1）')),
                ('implementation_complexity', models.CharField(choices=[('simple', '简单'), ('moderate', '中等'), ('complex', '复杂')], default='moderate', max_length=20, verbose_name='实施复杂性')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment_types', models.ManyToManyField(blank=True, to='equipment.equipmenttype', verbose_name='适用设备类型')),
            ],
            options={
                'verbose_name': '补偿措施',
                'verbose_name_plural': '补偿措施',
                'db_table': 'compensation_measures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EffectivenessEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(verbose_name='评估日期')),
                ('actual_effectiveness', models.FloatField(default=0.8, verbose_name='实际效果（0-1）')),
                ('notes', models.TextField(blank=True, verbose_name='评估备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('compensation_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_evaluations', to='compensation.compensationmeasure', verbose_name='补偿措施')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评估人')),
            ],
            options={
                'verbose_name': '有效性评估',
                'verbose_name_plural': '有效性评估',
                'db_table': 'effectiveness_evaluations',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='FailureModeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness_rating', models.CharField(choices=[('A', 'A - 优秀'), ('B', 'B - 良好'), ('C', 'C - 一般'), ('D', 'D - 较差'), ('E', 'E - 差'), ('F', 'F - 很差'), ('G', 'G - 无效')], default='C', max_length=1, verbose_name='效果评级')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('compensation_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_modes', to='compensation.compensationmeasure', verbose_name='补偿措施')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='failure.failuremode', verbose_name='故障模式')),
            ],
            options={
                'verbose_name': '故障模式补偿',
                'verbose_name_plural': '故障模式补偿',
                'db_table': 'failure_mode_compensations',
                'ordering': ['-created_at'],
                'unique_together': {('failure_mode', 'compensation_measure')},
            },
        ),
    ]
