# Generated by Django 4.2.7 on 2026-01-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='故障模式名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='故障模式编码')),
                ('description', models.TextField(blank=True, verbose_name='故障模式描述')),
                ('function_name', models.CharField(max_length=100, verbose_name='功能名称')),
                ('function_status', models.CharField(choices=[('1', '丧失功能'), ('2', '功能降级'), ('3', '功能无影响')], max_length=1, verbose_name='功能状态')),
                ('failure_effect', models.TextField(verbose_name='故障影响')),
                ('severity', models.CharField(choices=[('A', '极高'), ('B', '高'), ('C', '中等'), ('D', '低'), ('E', '极低')], max_length=1, verbose_name='严重性等级')),
                ('severity_score', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='严重性分数')),
                ('occurrence_rate', models.PositiveIntegerField(default=0, verbose_name='发生频率(%)')),
                ('frequency', models.CharField(blank=True, max_length=50, verbose_name='发生频率描述')),
                ('causes', models.TextField(blank=True, verbose_name='故障原因')),
                ('detection_methods', models.TextField(blank=True, verbose_name='检测方法')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_modes', to='equipment.equipmenttype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '故障模式',
                'verbose_name_plural': '故障模式',
                'db_table': 'failure_modes',
                'ordering': ['equipment_type', 'severity_score'],
            },
        ),
    ]
