# Generated by Django 4.2.7 on 2026-01-13 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('failure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='故障影响名称')),
                ('description', models.TextField(blank=True, verbose_name='故障影响描述')),
                ('severity', models.CharField(choices=[('A', '极高'), ('B', '高'), ('C', '中等'), ('D', '低'), ('E', '极低')], max_length=1, verbose_name='影响严重性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_effects', to='failure.failuremode', verbose_name='关联故障模式')),
            ],
            options={
                'verbose_name': '故障影响',
                'verbose_name_plural': '故障影响',
                'db_table': 'failure_effects',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FailureCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='故障原因名称')),
                ('description', models.TextField(blank=True, verbose_name='故障原因描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_causes', to='failure.failuremode', verbose_name='关联故障模式')),
            ],
            options={
                'verbose_name': '故障原因',
                'verbose_name_plural': '故障原因',
                'db_table': 'failure_causes',
                'ordering': ['name'],
            },
        ),
    ]
