# Generated by Django 4.2.7 on 2026-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failure', '0002_failureeffect_failurecause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuremode',
            name='name',
            field=models.CharField(max_length=100, verbose_name='故障模式名称'),
        ),
    ]
