# Generated by Django 4.2.7 on 2026-01-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failure', '0003_alter_failuremode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuremode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='故障模式编码'),
        ),
    ]
