# Generated by Django 4.2.7 on 2026-01-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设备类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备类型编码')),
                ('description', models.TextField(blank=True, verbose_name='设备类型描述')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='设备类别')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='制造商')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('specifications', models.JSONField(default=dict, verbose_name='技术规格')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'db_table': 'equipment_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='安装位置')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('warranty_expire_date', models.DateField(blank=True, null=True, verbose_name='保修到期日期')),
                ('status', models.CharField(choices=[('operational', '运行中'), ('maintenance', '维护中'), ('fault', '故障'), ('offline', '离线'), ('decommissioned', '已退役')], default='operational', max_length=20, verbose_name='状态')),
                ('custom_specifications', models.JSONField(default=dict, verbose_name='自定义规格')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='equipment.equipmenttype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备实例',
                'verbose_name_plural': '设备实例',
                'db_table': 'equipment_instances',
                'ordering': ['name'],
            },
        ),
    ]
