# Generated by Django 4.2.7 on 2026-01-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备类型编码'),
        ),
    ]
