# Generated by Django 4.2.7 on 2026-01-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipmenttype_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstance',
            options={'ordering': ['equipment_type', 'serial_number'], 'verbose_name': '设备实例', 'verbose_name_plural': '设备实例'},
        ),
        migrations.AlterField(
            model_name='equipmentinstance',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='序列号'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentinstance',
            unique_together={('equipment_type', 'serial_number')},
        ),
    ]
