# Generated by Django 4.2.7 on 2026-01-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipmenttype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstance',
            name='function_description',
            field=models.TextField(blank=True, verbose_name='功能描述'),
        ),
    ]
