# Generated by Django 4.2.7 on 2026-04-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_equipmenttype_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': '设备类型', 'verbose_name_plural': '设备类型'},
        ),
    ]
