# Generated by Django 4.2.7 on 2026-04-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipmenttype_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='install_date',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='warranty_expire_date',
        ),
    ]
