# Generated by Django 4.2.7 on 2026-04-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_remove_equipmentinstance_install_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstance',
            name='install_date',
            field=models.DateField(blank=True, null=True, verbose_name='安装日期'),
        ),
        migrations.AddField(
            model_name='equipmentinstance',
            name='warranty_expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='保修到期日期'),
        ),
    ]
