# Generated by Django 4.2.7 on 2026-01-04 12:20

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='权限名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='权限代码')),
                ('description', models.TextField(blank=True, verbose_name='权限描述')),
                ('module', models.CharField(max_length=50, verbose_name='所属模块')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'custom_permissions',
            },
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('permissions', models.JSONField(default=dict, verbose_name='权限配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'custom_roles',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='名字')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='姓氏')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('manager', '项目经理'), ('engineer', '工程师'), ('operator', '操作员'), ('viewer', '查看者')], default='viewer', max_length=20, verbose_name='用户角色')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('suspended', '暂停')], default='active', max_length=20, verbose_name='用户状态')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否为员工')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入日期')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users', related_query_name='custom_user', to='auth_app.customrole', verbose_name='自定义角色')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users', related_query_name='custom_user', to='auth_app.custompermission', verbose_name='自定义权限')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'custom_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
