# Generated by Django 4.2.7 on 2026-01-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('failure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='检测方法名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='检测方法编码')),
                ('description', models.TextField(blank=True, verbose_name='检测方法描述')),
                ('method_type', models.CharField(choices=[('inspection', '检测'), ('monitoring', '监控'), ('testing', '测试'), ('other', '其他')], default='inspection', max_length=20, verbose_name='方法类型')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本')),
                ('time_required', models.PositiveIntegerField(default=0, verbose_name='所需时间（分钟）')),
                ('accuracy', models.FloatField(default=0.95, verbose_name='准确率（0-1）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment_types', models.ManyToManyField(blank=True, to='equipment.equipmenttype', verbose_name='适用设备类型')),
            ],
            options={
                'verbose_name': '检测方法',
                'verbose_name_plural': '检测方法',
                'db_table': 'detection_methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('A', 'A - 几乎确定'), ('B', 'B - 非常高'), ('C', 'C - 高'), ('D', 'D - 中等'), ('E', 'E - 低'), ('F', 'F - 非常低'), ('G', 'G - 几乎不可能')], max_length=1, verbose_name='检测等级')),
                ('name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('description', models.TextField(blank=True, verbose_name='等级描述')),
                ('rpn_score', models.IntegerField(default=1, verbose_name='RPN分数')),
                ('detection_time', models.PositiveIntegerField(default=0, verbose_name='检测时间（分钟）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '检测评级',
                'verbose_name_plural': '检测评级',
                'db_table': 'detection_ratings',
                'ordering': ['rpn_score'],
            },
        ),
        migrations.CreateModel(
            name='FailureModeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('detection_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_modes', to='detection.detectionmethod', verbose_name='检测方法')),
                ('detection_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_modes', to='detection.detectionrating', verbose_name='检测评级')),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='failure.failuremode', verbose_name='故障模式')),
            ],
            options={
                'verbose_name': '故障模式检测',
                'verbose_name_plural': '故障模式检测',
                'db_table': 'failure_mode_detections',
                'ordering': ['-created_at'],
                'unique_together': {('failure_mode', 'detection_method')},
            },
        ),
    ]
