# Generated by Django 4.2.7 on 2026-01-13 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('failure', '0002_failureeffect_failurecause'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('severity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardAnalysisParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('parameter_type', models.CharField(choices=[('severity', '严酷度'), ('occurrence', '发生概率'), ('detection', '检测概率'), ('risk', '风险优先级')], max_length=20, verbose_name='参数类型')),
                ('description', models.TextField(blank=True, verbose_name='参数描述')),
                ('min_value', models.FloatField(verbose_name='最小值')),
                ('max_value', models.FloatField(verbose_name='最大值')),
                ('default_value', models.FloatField(verbose_name='默认值')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '危害度参数',
                'verbose_name_plural': '危害度参数',
                'db_table': 'hazard_analysis_parameters',
                'ordering': ['parameter_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FailureModeHazardAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_value', models.FloatField(verbose_name='严酷度值')),
                ('occurrence_probability', models.FloatField(verbose_name='发生概率(%)')),
                ('detection_probability', models.FloatField(verbose_name='检测概率(%)')),
                ('risk_priority_number', models.FloatField(verbose_name='风险优先级数(RPN)')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中等风险'), ('high', '高风险'), ('critical', '严重风险')], max_length=20, verbose_name='风险等级')),
                ('analysis_date', models.DateField(auto_now_add=True, verbose_name='分析日期')),
                ('notes', models.TextField(blank=True, verbose_name='分析说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('failure_mode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_analysis', to='failure.failuremode', verbose_name='故障模式')),
                ('severity_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_analyses', to='severity.severitylevel', verbose_name='严酷度等级')),
            ],
            options={
                'verbose_name': '故障模式危害度分析',
                'verbose_name_plural': '故障模式危害度分析',
                'db_table': 'failure_mode_hazard_analyses',
                'ordering': ['-risk_priority_number', '-severity_value'],
            },
        ),
    ]
