# Generated by Django 4.2.7 on 2026-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failure_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuremodehazardanalysis',
            name='recommended_action',
            field=models.TextField(blank=True, verbose_name='使用补偿措施'),
        ),
    ]
