# Generated by Django 4.2.7 on 2026-01-13 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0002_alter_equipmenttype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHazardAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(auto_now_add=True, verbose_name='分析日期')),
                ('total_failure_modes', models.PositiveIntegerField(default=0, verbose_name='总故障模式数')),
                ('analyzed_failure_modes', models.PositiveIntegerField(default=0, verbose_name='已分析故障模式数')),
                ('avg_severity', models.FloatField(default=0, verbose_name='平均严酷度')),
                ('avg_occurrence', models.FloatField(default=0, verbose_name='平均发生概率(%)')),
                ('avg_detection', models.FloatField(default=0, verbose_name='平均检测概率(%)')),
                ('avg_rpn', models.FloatField(default=0, verbose_name='平均风险优先级数(RPN)')),
                ('max_rpn', models.FloatField(default=0, verbose_name='最高RPN值')),
                ('min_rpn', models.FloatField(default=0, verbose_name='最低RPN值')),
                ('critical_count', models.PositiveIntegerField(default=0, verbose_name='严重风险数')),
                ('high_count', models.PositiveIntegerField(default=0, verbose_name='高风险数')),
                ('medium_count', models.PositiveIntegerField(default=0, verbose_name='中等风险数')),
                ('low_count', models.PositiveIntegerField(default=0, verbose_name='低风险数')),
                ('overall_risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中等风险'), ('high', '高风险'), ('critical', '严重风险')], max_length=20, verbose_name='整体风险等级')),
                ('assessment_conclusion', models.TextField(blank=True, verbose_name='评估结论')),
                ('recommendations', models.TextField(blank=True, verbose_name='改进建议')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_analyses', to='equipment.equipmenttype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '产品危害度分析',
                'verbose_name_plural': '产品危害度分析',
                'db_table': 'product_hazard_analyses',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
