# Generated by Django 4.2.7 on 2026-01-13 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('failure', '0002_failureeffect_failurecause'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Ⅰ', 'Ⅰ级（灾难性）'), ('Ⅱ', 'Ⅱ级（严重）'), ('Ⅲ', 'Ⅲ级（中等）'), ('Ⅳ', 'Ⅳ级（轻微）')], max_length=2, unique=True, verbose_name='严酷度等级')),
                ('name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('description', models.TextField(verbose_name='等级描述')),
                ('criteria', models.TextField(verbose_name='评定标准')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, unique=True, verbose_name='等级分数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '严酷度等级',
                'verbose_name_plural': '严酷度等级',
                'db_table': 'severity_levels',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='SeverityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='指标名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='指标编码')),
                ('description', models.TextField(verbose_name='指标描述')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='指标权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '严酷度指标',
                'verbose_name_plural': '严酷度指标',
                'db_table': 'severity_indicators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeverityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='评定分数')),
                ('evaluation', models.TextField(verbose_name='评定说明')),
                ('evidence', models.TextField(blank=True, verbose_name='评定依据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severity_assessments', to='failure.failuremode', verbose_name='故障模式')),
                ('severity_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='severity.severitylevel', verbose_name='严酷度等级')),
            ],
            options={
                'verbose_name': '严酷度评定',
                'verbose_name_plural': '严酷度评定',
                'db_table': 'severity_assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
