# Generated by Django 4.2.7 on 2026-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='severityassessment',
            name='detection_value',
            field=models.IntegerField(default=1, help_text='范围1-10', verbose_name='检测度D'),
        ),
        migrations.AddField(
            model_name='severityassessment',
            name='occurrence_value',
            field=models.IntegerField(default=1, help_text='范围1-10', verbose_name='发生度O'),
        ),
        migrations.AddField(
            model_name='severityassessment',
            name='rpn_value',
            field=models.IntegerField(default=1, help_text='由S×O×D计算得出', verbose_name='风险优先数RPN'),
        ),
        migrations.AddField(
            model_name='severityassessment',
            name='severity_value',
            field=models.IntegerField(default=1, help_text='范围1-10', verbose_name='严酷度S'),
        ),
    ]
