# Generated by Django 4.2.7 on 2026-01-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severity', '0003_alter_severityassessment_evaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='severityassessment',
            options={'ordering': ['created_at'], 'verbose_name': '严酷度评定', 'verbose_name_plural': '严酷度评定'},
        ),
        migrations.AddField(
            model_name='severityassessment',
            name='project_instance_name',
            field=models.CharField(default='', max_length=255, verbose_name='项目实例名称'),
        ),
    ]
