# Generated by Django 4.2.7 on 2026-02-07 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('auto', '跟随系统')], default='light', max_length=10, verbose_name='主题')),
                ('language', models.CharField(choices=[('zh-CN', '简体中文'), ('en-US', 'English')], default='zh-CN', max_length=10, verbose_name='语言')),
                ('page_size', models.IntegerField(default=20, verbose_name='每页显示条数')),
                ('auto_save', models.BooleanField(default=True, verbose_name='自动保存')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('system_enabled', models.BooleanField(default=True, verbose_name='系统通知')),
                ('failure_alert', models.BooleanField(default=True, verbose_name='故障提醒')),
                ('analysis_complete', models.BooleanField(default=True, verbose_name='分析完成提醒')),
                ('report_ready', models.BooleanField(default=True, verbose_name='报告生成提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
                'db_table': 'user_settings',
            },
        ),
    ]
